### ISSUE TITLE
How to add volume on Jellyfin docker

### ISSUE THREAD

**Issue by Astate** [petersendev/hassio-addons#46]
How to add volume on Jellyfin docker.

with Samba NAS addond i added DATAPI volume from volume ID. Can i do same with Jellyfin ?

**Comment by petersendev** [comment]
Hi, all my addons assume files living in the share mount from home assistant, so in case for jellyfin:

- /share/storage/tv
- /share/storage/movies

I mount my nas shares to the share/storage folder on the home assistant (former hassio) host, so I don't have to maintain the shares everywhere. Since the whole share folder will be mounted to /share by home assistant, everything you mount on the host will be available for the addons.

Hope that helps, if not feel free to repopen

**Comment by bboudewijns** [comment]
Hi! Thanks for the very nice add-ons! Much appreciated. 

I do have a question though. I am running hassOS on a Intel nuc and I mounted the video folder on my NAS exactly as you said. In terminal with ls it does list all my movies. But when I add that folder to the media library of Jellyfin, nothing is indexed. 

Can you give me a tip please in what I might be doing wrong here? 

Thanks in advance!

**Comment by alexbelgium** [comment]
@bboudewijns hi, did you solve this issue? I think that we have a similar issue : if I mount a smb folder in /share on hassio I can see the files using terminal, but they don't get indexed by emby/jellyfin. Thanks!

**Comment by bboudewijns** [comment]
No, unfortunately the issue still exist as I was waiting on a reply. I currently have Jellyfin running on my Synology NAS, so I am not in a hurry, but would love to use it with this add-on instead.

**Comment by petersendev** [comment]
This is strange.

Here are some more details from my config, hoping that it helps:

Home Assistant folder on host: ```/opt/hassio```
Example fstab entry: 
```
//nas/Movies /opt/hassio/share/storage/movies cifs uid=dockeruser,gid=dockeruser,file_mode=0664,dir_mode=0770,credentials=/root/.smbcredentials,iocharset=utf8,sec=ntlmssp,rsize=32768,wsize=32768,cache=none,vers=1.0 0
```

Path in the container: ```/share/storage/movies```

You might need to restart docker for it to pick up the mount.

**Comment by alexbelgium** [comment]
Hi, it seems that the issue stems from differences in permissions between containers in hassOs. I tried running the addon as root but it didn't help - I read that we needed to create a new user both in the container and in hassOs and allocate permissions but couldn't find how ;-)

In the end, the way I solved it was to fork your addon and do the following :
- add priviliged and full_access flags to the config.json
- manually go in the container console using Portainer to run "mount /dev/sda1 /share/hdd". I'm sure it would have worked with cifs but in the end I connected it manually

I tried to add the "mount" code directly in the addon start-up code, and add the external disk and mountpoint in the addon config but couldn't a way to make it work... ;-) but well I'm happy enough for now!

**Comment by petersendev** [comment]
You just need a user on the host (at least for cifs) which is used for the mount and the addon.

From my example above, the dockeruser is 1001:1001 which I set in the addon config:
```yaml
PUID: 1001
PGID: 1001
```

**Comment by alexbelgium** [comment]
Hi @petersendev, thanks for your patience in answering us on this thread. I'm coming back but I've spent hours trying to make it work, and couldn't make it work.

I'm using "home assistant" on an rpi 3b+. It seems that fstab is disabled on the host (at least that's what it says when I open it), and that that mounts can't propagate from one docker container to the other. My understanding of docker containers from what I read is that mounted shared can't be propagated from one container to the other. After reading a lot on Hassio forums, I've managed to mount smb using : 
- CLI (but the content is only visible in CLI addon)
- shell scripts (but the content is only visible in media browser as it depends from the homeassistant container)
- portainer (but the shared drive is removed at each reboot)

The only way would therefore be to mount the smb share at addon boot... Would you consider adding an option to mount smb at boot provided that we add the server, user name & password ? To achieve that, it would need to apt-get update cifs-utils and then execute a "mount cifs"...

Actually I've tried to fork your addon but couldn't find how to inject commands in the addon start sequence :-) I would understand if my usage is too specific and that it would request too much work for you to implement that. I'm already very grateful for you to provide us this addon!

**Comment by petersendev** [comment]
Mounting directly in each addon doesn't make much sense for me.
Home Assistant shares it's folders (which you can see if accessing the smb addon share) with each addon that want's it. That is configured in the map section in the addon config.
You should have a /config, /share etc folder in the emby container. That's how all the addon config and data is persisted.

If you want to mount your own folders, the way I descibed above is mounting the shares on the host in one of these folders.
If the permissions are set correctly (need owner settings in mount command and addon config, see above) the mounted folder should be accessible in the container (as I said, you may need to restart).

As long as it is showing on the host, it should show in the containers.

**Comment by alexbelgium** [comment]
Thanks very much. I've re-read all your messages and understand your point. I thought the host fstab was disabled (when I open it by connecting a keyboard & hdmi directly to the rpi, there is a message saying not to use it) but I'll try again to edit fstab & mount it directly on the hassio host.
