### ISSUE TITLE
Latest version of mobile app not compatible with current version of server

### ISSUE THREAD

**Issue by atmdev** [petersendev/hassio-addons#67]
Hello,
When I connect the most recent Android mobile app of Jellyfin (2.2.0) to the server (10.5.5), I get this error message: "Le serveur utilise une version non supportée. Migrez vers la dernière version disponible sur jellyfin.org". It works with an older version of the mobile app.
Do you think it would be possible to upgrade the base image?
Thanks!

**Comment by petersendev** [comment]
Seems like the base image versioning scheme has changed so new versions weren't picked up, should be fixed now.

**Comment by atmdev** [comment]
Thanks for your quick reaction 👍 
It is working fine now.
