### ISSUE TITLE
Transmission OVPN: can't find mnt point for custom .ovpn 

### ISSUE THREAD

**Issue by Cactusoase** [petersendev/hassio-addons#77]
Trying to make transmissionovpn work with a custom vpn, however I'm having issues finding the mount point where these files could be placed (.ovpn file/.crt/.cta)

Within Portainer the data share should be: /mnt/data/supervisor/addons/data/fec04c7c_transmission-openvpn 
mounted at: /data
However I can only find the mounts at /mnt/data/supervisor/addons/data/**transmission-openvpn** which is where downloads etc are placed.

from the log:
Using OpenVPN provider: CUSTOM
Supplied config default.ovpn could not be found.

Can someone point me in the right direction?

**Comment by petersendev** [comment]
See #76 for an example how to use the custom .ovpn

**Comment by jflecool2** [comment]
#76 is different issue. Here's the correct link: https://github.com/petersendev/hassio-addons/issues/65#issuecomment-735005801
