### ISSUE TITLE
Remote share for sonarr/radarr

### ISSUE THREAD

**Issue by CrazySummerr** [petersendev/hassio-addons#78]
Hi,
I have my media files on NAS and my HASSIO installation on Raspberry. I installed your addon and sonar is starting. 
In the configuration "import existing series on disk" I can only see folder on my raspberry.

In terminal when I try to mount a folder I get "permission denied"

Can you advise how to fix it?

BR

**Comment by petersendev** [comment]
You have to mount the folder on your host, using one of the shared folders from home assistant (share or media).
You can find some examples in #46
