### ISSUE TITLE
NZBGet - (Relatively) High CPU usage while idle

### ISSUE THREAD

**Issue by Ruco** [petersendev/hassio-addons#79]
Hi,

Thank you very much for your awesome work. Very useful to have these addons available.

I noticed that all of the addons I've tested thusfar have a low impact on the system (Rpi4 8Gb).
Yet NZBGet, doing nothing but sitting idly waiting for something to download, already has a relatively high CPU load (with consequently increased CPU temp) of around 25-30%.

Any idea of the cause for this? And a solution to bring this down?
Is there anyway I can check what's keeping it so busy?

Thank you kindly.

**Comment by petersendev** [comment]
The addon's are based on images from linuxserver.io, they just include some path changes to make them compatible with home assistant addon environment.

Can't really do anything performance wise here, sorry
