### ISSUE TITLE
Emby NAS Warning log: Add-on have full device access....in the configuration

### ISSUE THREAD

**Issue by duceduc** [petersendev/hassio-addons#87]
I am noticing this warning in the Supervisor log. Not sure why it is showing up since I have never installed the add-on.

>Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Emby NAS

Warning:
![2021-05-29_15-54-10](https://user-images.githubusercontent.com/20457723/120061184-fb610900-c096-11eb-8332-2e80cf4e05cb.jpg)

Add-on:
![2021-05-29_15-55-08](https://user-images.githubusercontent.com/20457723/120061191-0156ea00-c097-11eb-8e74-6fdf86758be2.jpg)

Core Version: 2021.5.5
Supervisor Version: 2021.04.3

**Comment by petersendev** [comment]
That are not my addons, so I can't help you with that.
The screenshot mentions "alexbegium", you should try to contact him instead.
