### ISSUE TITLE
Jellyfin missing dockerfile 0.10.0

### ISSUE THREAD

**Issue by llewy** [petersendev/hassio-addons#91]
![BACB1739-B7B8-4875-85D1-19A0A89F1B4A](https://user-images.githubusercontent.com/525767/124314447-b38c4080-db72-11eb-9a54-a4c9dbcdda22.jpeg)
![98C7191E-6943-4DA1-BF8A-EACEA7899976](https://user-images.githubusercontent.com/525767/124314462-b9822180-db72-11eb-837e-e9e4ba5794b2.jpeg)

**Comment by petersendev** [comment]
Interestting, the build for the master branch wasn't triggered, not really sure why.
I'll keep an eye out for that, image should be available now.

Thank you very much for letting me know!
