### ISSUE TITLE
heimdall: can't start due to ssl generation errors

### ISSUE THREAD

**Issue by BuildTheRobots** [petersendev/hassio-addons#94]
After installing the Heimdall plugin, I get the following error when trying to start it:

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-ha-env: executing... 
[cont-init.d] 00-ha-env: exited 0.
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 20-folders: executing... 
[cont-init.d] 20-folders: exited 0.
[cont-init.d] 30-keygen: executing... 
generating self-signed keys in /config/heimdall/keys, you can replace these with your own keys if required
Generating a RSA private key
........................................................+++++
........................................................................................................................................+++++
writing new private key to '/ssl/privkey.pem'
req: Can't open "/ssl/privkey.pem" for writing, Read-only file system
[cont-init.d] 30-keygen: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.```

**Comment by petersendev** [comment]
hmm, i see the problem.
The cert's shouldn't be generated by the addon, because it is supossed to use the home assistant certs.
But if you don't use SSL in home assistant, this doesn't work.

Workaround would be to enable SSL for home assistant (for example Let's encrypt addon).

I don't have a solution for that right now, since heimdall doesn't seem to have a non-ssl option. Maybe linking to the files if present and if not building them in another path or something? Would welcome PRs for this.

**Comment by petersendev** [comment]
this should work now, please let me know if it does for you

**Comment by BuildTheRobots** [comment]
Sincerest apologies for not replying sooner and a massive thank you for patching this.

LetsEncrypt is a fantastic service, however as I don't have inbound access for any of the services running in my house (I use a VPN for RA), making using LE rather difficult. Ironically, the only reason I tried to install Heimdall on the Pi was because I'm setting up nginx as a reverse proxy (using self signed certs) and wanted to have a sensible landing page (for when I couldn't remember the subdomin of whichever service I was trying to access)

I ended up deleting the /config/heimdall folder, updated the addon and restarted and it all seems to be working as expected now - greatest of thanks :)

**Comment by petersendev** [comment]
Nice, thanks for the feedback.

I personally use Let's Encrypt for local only, using that cert in nginx proxymanager for all my internal stuff just so i have clean ssl worth the option for external access in the future.
